###############################
# Motrix AI Aria2 config file
# Based on motrix-next's proven configuration
# @see https://aria2.github.io/manual/en/html/aria2c.html
###############################

################ RPC ################
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=false

################ TLS ################
check-certificate=false

################ File system ################
auto-save-interval=10
disk-cache=64M
file-allocation=trunc
no-file-allocation-limit=64M
save-session-interval=10

################ Task ################
max-file-not-found=10
max-tries=0
retry-wait=10
connect-timeout=10
timeout=10
async-dns=false
min-split-size=1M
http-accept-gzip=true
remote-time=true
auto-file-renaming=true
continue=true
max-concurrent-downloads=5
max-connection-per-server=16
split=16

################ BT ################
bt-enable-lpd=true
bt-max-peers=128
bt-seed-unverified=false
enable-dht=true
enable-dht6=true
enable-peer-exchange=true
follow-torrent=true
dht-entry-point=dht.transmissionbt.com:6881
dht-entry-point6=dht.transmissionbt.com:6881
